yiisoft/yii2-mongodb

- docs/guide-ja/README.md
- docs/guide-ja/topics-i18n-message-source.md
Japanese translation of the documentation updated.
> docs/guide-ja updated [skip ci]

- Query.php
- debug/ExplainAction.php
- debug/MongoDbPanel.php
- docs/guide/topics-debug.md
I add explain queries in debug panel and method in Query class.
fixes #74
> Added ability to EXPLAIN queries in Debug panel

- CHANGELOG.md
- rbac/MongoDbManager.php
- rbac/Permission.php
- rbac/Role.php
- tests/data/rbac/ActionRule.php
- tests/data/rbac/AuthorRule.php
- tests/rbac/MongoDbManagerTest.php
| Is bugfix?    | no
| New feature?  | yes
| Fixed issues  | #87
> RBAC manager

- docs/guide-ja/topics-debug.md
document translation (ja) updated
> Docs ja 0509 [ci skip]

- .travis.yml
- file/ActiveQuery.php
- file/ActiveRecord.php
- file/Collection.php
- file/Cursor.php
- file/Download.php
- file/Query.php
- file/Upload.php
- tests/TestCase.php
- tests/file/ActiveRecordTest.php
- tests/file/CollectionTest.php
- tests/file/DownloadTest.php
- tests/file/QueryTest.php
- tests/file/UploadTest.php
| Breaks BC?    | yes
| Fixed issues  | #117
> Fix #117 New Driver GridFS implementation

- ActiveQuery.php
- BatchQueryResult.php
- CHANGELOG.md
- Query.php
- file/ActiveQuery.php
- tests/BatchQueryResultTest.php
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Fixed issues  | #77
> Fix #77 Added support for fetching data from MongoDB in batches

- Connection.php
- file/Cursor.php
- file/Download.php
- file/StreamWrapper.php
- file/Upload.php
- tests/file/ActiveRecordTest.php
- tests/file/StreamWrapperTest.php
- tests/file/UploadTest.php
> Fix #120 stream wrapper

- .travis.yml
- tests/data/travis/mongodb-setup.sh
Related to #119 
Travis installation simplied
> Travis Update 

- CHANGELOG.md
- file/StreamWrapper.php
- tests/file/StreamWrapperTest.php
| Breaks BC?    |
| Fixed issues  | #147
> added unknown methods for fseek and ftell, according #147

- docs/guide-fr/README.md
- docs/guide-fr/installation.md
add installations.md
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> documentations to fr

- CHANGELOG.md
- console/controllers/MigrateController.php
to be merged when https://github.com/yiisoft/yii2/pull/14241 is ready.
> forward compatibility with Yii 2.0.12

- Query.php
| Is bugfix?    | documentation bug
| Tests pass?   | -
| Fixed issues  | -
> Tiny phpdoc fix in Query::andFilterCompare() [skip ci]

- CHANGELOG.md
- docs/guide/topics-i18n-message-source.md
- i18n/MongoDbMessageSource.php
- tests/i18n/MongoDbMessageSourceTest.php
| New feature?  | yes
| Fixed issues  | #158
> Fix #158: message source data strucutre

- composer.json
| Is bugfix?    | no
| Fixed issues  | yii 3.0
>  Update composer.json (2.1 => 3.0)

- .github/workflows/build.yml
- tests/data/config.php
> Try github actions

- .github/workflows/build.yml
- README.md
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> Enhance workflow

- .github/workflows/build.yml
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> Make workflow simpler

- .github/workflows/build.yml
- CHANGELOG.md
- src/BatchQueryResult.php
> Compatibility with 1.9.0 driver

- docs/guide-ja/usage-gridfs.md
- docs/guide-ru/usage-gridfs.md
- docs/guide/usage-gridfs.md
> Fixing some possible typos in docs

- src/QueryBuilder.php
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |
> Fix-make-download-for-site

- docs/guide-fr/installation.md
- docs/guide-ja/installation.md
- docs/guide-ru/installation.md
- docs/guide/installation.md
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  |
> update docs folder links

- src/Connection.php
- src/Session.php
- src/file/StreamWrapper.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-mongodb/issues/364
> update src folder links

- README.md
- UPGRADE.md
- composer.json
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-mongodb/issues/366
> update root folder links

- CHANGELOG.md
- src/gii/model/Generator.php
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |
>  fix #373: fix generator trim and strtolower causes exception in PHP8.1

- UPGRADE.md
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-mongodb/issues/376
> update root folder link
